In [1]:
import numpy as np
import pandas as pd

In [8]:
path = '../data/long-minor axis.csv'
data = pd.read_csv(path)
data.head()

   long axis  minor axis
0        240          37
1        145          70
2         85          25
3         65          36
4        100         100

In [9]:
long_axis = data[['long axis']]
minor_axis = data[['minor axis']]
long_axis, minor_axis

(    long axis
 0         240
 1         145
 2          85
 3          65
 4         100
 5         115
 6         205
 7          60
 8         185
 9          75
 10        105
 11        150
 12         33
 13         65
 14        160
 15        200
 16        225
 17         75
 18         60
 19         80
 20         55
 21         55
 22         37
 23         60
 24         36
 25         25
 26         80
 27         45
 28        280
 29        120
 30        180
 31         50
 32        155
 33        145
 34         27
 35        100
 36         45
 37        185
 38         20
 39        240
 40         50
 41        160
 42        195
 43        315
 44        160
 45         75
 46         31,
     minor axis
 0           37
 1           70
 2           25
 3           36
 4          100
 5           90
 6          120
 7           17
 8           85
 9           26
 10          75
 11          70
 12          31
 13          50
 14          50
 15          60
 16          45
 17          50
 18          36
 19          39
 20          23
 21          27
 22          35
 23          34
 24          19
 25          30
 26          50
 27          13
 28          85
 29          95
 30          45
 31          55
 32          65
 33          70
 34          21
 35          23
 36          22
 37          75
 38          13
 39          85
 40          40
 41          40
 42          85
 43          50
 44          70
 45          52
 46          13)

In [10]:
long = np.array(long_axis)
minor = np.array(minor_axis)
long.shape,minor.shape
temp = minor/long
temp = 1- temp*temp
e = np.sqrt(temp)
print(e)

[[0.98804486]
 [0.87575346]
 [0.95576922]
 [0.83261902]
 [0.        ]
 [0.62251396]
 [0.81076928]
 [0.95902149]
 [0.88819874]
 [0.93798839]
 [0.69985421]
 [0.88443328]
 [0.34283965]
 [0.63897107]
 [0.94991776]
 [0.9539392 ]
 [0.9797959 ]
 [0.74535599]
 [0.8       ]
 [0.87312299]
 [0.90836335]
 [0.8712108 ]
 [0.32432432]
 [0.82394714]
 [0.84938249]
 [       nan]
 [0.78062475]
 [0.95736263]
 [0.95280868]
 [0.61095326]
 [0.96824584]
 [       nan]
 [0.90782241]
 [0.87575346]
 [0.62853936]
 [0.97319063]
 [0.87234606]
 [0.914137  ]
 [0.75993421]
 [0.93518232]
 [0.6       ]
 [0.96824584]
 [0.89999635]
 [0.987322  ]
 [0.89921841]
 [0.72061702]
 [0.90782241]]

C:\Users\didhw\AppData\Local\Temp/ipykernel_20532/2041280830.py:6: RuntimeWarning: invalid value encountered in sqrt
  e = np.sqrt(temp)